import Head from 'next/head';
import Image from 'next/image';
import AppRight from '../components/AppRight';

export default function Home() {
  return (
    <div className="flex">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          background:
            'url(https://res.cloudinary.com/dssvrf9oz/image/upload/v1622735422/mads-schmidt-rasmussen-xfngap_DToE-unsplash_k3yczw.jpg)',
          flex: '0.6',
        }}
        className="font-poppins flex flex-col h-screen justify-center items-center !bg-cover !bg-bottom object-contain rounded-r-3xl "
      >
        <h2 className="absolute top-10 left-10 text-2xl font-bold text-white">
          TooTravel
        </h2>
        <div className="flex flex-col w-3/5">
          <h2 className="text-5xl font-semibold text-white">
            The most beautiful places in the world!
          </h2>
          <p className="text-white text-sm mt-10">
            Plan your vacation on the most beatiful places in the world
          </p>
          <button className="bg-orange w-60 h-10 mt-10 text-[#fff] py-2 px-5 rounded-xl">
            Get started
          </button>
        </div>
      </div>
      <div className="absolute bottom-10 left-20 flex items-center cursor-pointer ">
        <p className="text-white">01</p>
        <div className="h-[2px] w-10 bg-white mr-2 "></div>
        <div className="h-[2px] w-10 bg-white mr-2 bg-opacity-20 hover:bg-opacity-100"></div>
        <div className="h-[2px] w-10 bg-white mr-2 bg-opacity-20 hover:bg-opacity-100"></div>
        <p className="text-white">03</p>
      </div>
      <div style={{ flex: '0.4' }} className="">
        <AppRight />
      </div>
    </div>
  );
}
